name: Fetch Figma Data

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows for manual triggering

jobs:
  fetch-figma:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Fetch Figma Data
        env:
          FIGMA_API_TOKEN: ${{ secrets.FIGMA_API_TOKEN }}
        run: node fetchFigma.js

      - name: Commit and Push changes
        run: |
          git config --local user.email lexarce7@gmail.com
          git config --local user.name Alexis Arce
	  git restore package-lock.json # Revert changes to package-lock.json
          git add figmaData.json
          git commit -m "Update Figma data [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

